name: Economy
author: Nick Lersberghe - Lazoh - MyNameIsLego
version: 1.0
main: econMain.Main
description: Plugin that enables an economy. Adds a currency. Allows for money transfer, player shops and auctions.
commands:
    auction:
        usage: /<command> [option1] [option2]
        description: The basic Auction command. Use '/auction info' for info, '/auction time' for remaining time. '/auction [amount] [price]' to start an auction. '/auction bid [price]' to bid on an auction.
        aliases: [auc]
        
permissions:
    econ.configEcon:
        description: Being able to configurate Economy's settings.
        default: op
    econ.transfer:
        description: Being able to edit a Player's funds without their consent.
        default: op
        
        

